# Generated by Django 4.1.2 on 2022-12-26 10:30

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('heading', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('image2', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
                ('image3', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
                ('image4', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
                ('heading', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=4000)),
                ('offer1', models.TextField(max_length=500)),
                ('offer2', models.TextField(max_length=500)),
                ('offer3', models.TextField(max_length=500)),
                ('offer4', models.TextField(max_length=500)),
                ('roomSize', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=4000)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.villa')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=4000)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.villa')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=4000)),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Dining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('heading', models.TextField(max_length=100)),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('description', models.TextField(max_length=4000)),
                ('timeline', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.villa')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='villa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.villa'),
        ),
    ]
