# Generated by Django 4.1.2 on 2022-12-29 10:32

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='catchy_phrase',
            field=models.CharField(default='Land of the Free', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=pyuploadcare.dj.models.ImageField(default=''),
        ),
        migrations.AddField(
            model_name='country',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
