# Generated by Django 4.1.2 on 2023-01-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='price',
            new_name='old_price',
        ),
        migrations.AddField(
            model_name='offer',
            name='complimentary1',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='complimentary2',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='complimentary3',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='complimentary4',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
        migrations.AddField(
            model_name='offer',
            name='inclusion1',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='inclusion2',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='inclusion3',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='inclusion4',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='inclusion5',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='term1',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='term2',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='term3',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='term4',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='term5',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='villa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.villa'),
        ),
    ]
