# Generated by Django 4.1.2 on 2022-12-30 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_country_catchy_phrase_country_image_country_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='catchy_phrase',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.tag'),
        ),
    ]
