# Generated by Django 4.1.5 on 2023-04-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_date_joined_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
