# Generated by Django 4.1.2 on 2022-12-30 19:29

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag_alter_country_catchy_phrase_alter_country_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description1',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='country',
            name='description2',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='country',
            name='image_toper',
            field=pyuploadcare.dj.models.ImageField(default=''),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
