# Generated by Django 4.1.2 on 2023-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_offer_offerdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
