# Generated by Django 4.1.2 on 2023-01-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_country_video_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dining',
            new_name='Restaurant',
        ),
        migrations.RemoveField(
            model_name='country',
            name='video_file',
        ),
    ]
