# Generated by Django 4.1.2 on 2023-01-03 15:46

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_dining_restaurant_remove_country_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='villa',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='catchy_phrase',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gallery1',
            field=pyuploadcare.dj.models.ImageField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gallery2',
            field=pyuploadcare.dj.models.ImageField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gallery3',
            field=pyuploadcare.dj.models.ImageField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='info1',
            field=models.TextField(default='', max_length=100),
        ),
    ]
