# Generated by Django 4.1.2 on 2023-01-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_restaurant_villa_restaurant_catchy_phrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='info2',
            field=models.TextField(default='', max_length=100),
        ),
    ]
