# Generated by Django 4.1.2 on 2023-01-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_restaurant_info2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='info2',
        ),
    ]
