# Generated by Django 4.1.2 on 2023-01-04 08:00

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_restaurant_info2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sustainability',
            new_name='Contact',
        ),
        migrations.DeleteModel(
            name='Wedding',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='text',
            new_name='text1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_cover',
            field=pyuploadcare.dj.models.ImageField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.tag'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='text2',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='text3',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
    ]
