# Generated by Django 4.1.5 on 2023-01-08 16:43

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='video',
            field=pyuploadcare.dj.models.FileField(blank=True, default='', null=True),
        ),
    ]
