# Generated by Django 4.1.5 on 2023-01-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_country_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='video',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
