# Generated by Django 4.1.5 on 2023-01-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_country_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='video',
            new_name='video_url',
        ),
    ]
